### PR TITLE
[BUGFIX] (Correctly) Fail on Mismatched Numbers of Expected & Observed Examples

### LINKED ISSUE #127: Tests do not Check that Expected and Generated Outputs have Same Number of Sentences
This issue concerns the following line in the main test script:

https://github.com/GEM-benchmark/NL-Augmenter/blob/27ab1d7163100b133648846a18935cb6f2a137ee/test/test_main.py#L26

[The `zip()` builtin](https://docs.python.org/3/library/functions.html#zip) (which is used in the above-mentioned line to pair up expected sentences with generated sentences) clips the longer of its two inputted iterables to the length of the shorter iterable. E.g.:

```python
>>> list(zip([1,2,3], [6,7,8,9,10]))
[(1, 6), (2, 7), (3, 8)]
```

This means that even if a transformation generates fewer sentences (e.g. 0) than the expected number of sentences, it will still pass and the later expected sentences will not get evaluated. This also makes it impossible to test affirmatively that a transformation does not generate any outputs for a given input.

I would recommend either `assert`ing that the two iterables are of equal length, or replacing `zip()` with [`zip_longest()`](https://docs.python.org/3/library/itertools.html#itertools.zip_longest).

### PR DESCRIPTION
**Pull request by cascadianblue**
Fixes #127 .

### CODE REVIEW

**Comment by kaustubhdhole** [comment]
Seems the build is failing because of a prediction in GenderCultureDiverseName:  

E           AssertionError: Mis-match in expected and predicted output for GenderCultureDiverseName transformation: 
E              Expected Output: Rihab Buffay is an eccentric masseuse and musician. 
E              Predicted Output: None
E           assert None == 'Rihab Buffay is an eccentric masseuse and musician.'

**Comment by cascadianblue** [comment]
> Seems the build is failing because of a prediction in GenderCultureDiverseName:

@kaustubhdhole I think this is a real example of the bug. The test case is expecting one sentence to be outputted:

`expected = ["Rihab Buffay is an eccentric masseuse and musician."]`

but the actual transformation is outputting no sentences:

`actual = []`

and `pairs = zip(expected, actual) = []`, therefore, when it iterates through those `pairs`, it's just an empty loop.

**Comment by cascadianblue** [comment]
Should we "fix" the test cases of the already existing transformations as part of this PR?

**Comment by kaustubhdhole** [comment]
Thank you for your efforts @cascadianblue! It would be smoother to change the test cases in this PR itself as the build needs to be always kept green :)

**Comment by cascadianblue** [comment]
@kaustubhdhole hmmm, I had assumed that lots of other tests would have this problem, but it looks like `gender_culture_diverse_name` might have been the only one

**Comment by kaustubhdhole** [comment]
Adding @XudongOliverShen once to confirm.

**Comment by cascadianblue** [comment]
@kaustubhdhole did you mean to request @XudongOliverShen for review? I only see you on the reviewers list

**Comment by XudongOliverShen** [comment]
Looks good to me! 

Removing incorrect test cases is okay, so the build is green. After this PR is merged, I will update `GenderCultureDiverseName` to add back proper test cases.

**Comment by kaustubhdhole** [comment]
@cascadianblue I just meant to keep @XudongOliverShen in loop :)

**Review by kaustubhdhole — APPROVED** [review]

**Comment by kaustubhdhole** [comment]
Thanks @cascadianblue for making this change!

**Pull request merged**
