### PR TITLE
Gender bias filter pull request

### PR DESCRIPTION
**Pull request by asnota**

### CODE REVIEW

**Comment by AbinayaM02** [comment]
Hi @asnota : I think the PR has changes related to two filters. I would suggest you to first fetch upstream on your "NL-Augmenter"  repository and then git clone and create a new branch and copy only the gender_bias changes and update this PR.

**Comment by asnota** [comment]
Hi @AbinayaM02 the discrimination filter was also approved (pull request #285), but I'll follow the procedure you've described.

**Comment by AbinayaM02** [comment]
Hi @asnota: I think you have deleted the gender_bias files as well by mistake. Please commit the gender_bias changes.

**Comment by asnota** [comment]
Hi @AbinayaM02 indeed I deleted both on purpose - I cleaned the main branch from my filters (result of the fetching of the main branch to my version of the fork) and from a cleaned main I created a new branch gender_bias_filter_integration, which contains the gender bias filter only. I opened a related pull request in #286

**Comment by AbinayaM02** [comment]
> Hi @AbinayaM02 indeed I deleted both on purpose - I cleaned the main branch from my filters (result of the fetching of the main branch to my version of the fork) and from a cleaned main I created a new branch gender_bias_filter_integration, which contains the gender bias filter only. I opened a related pull request in #286

Okay, missed the new PR. Let me close the duplicate PRs.

**Pull request closed without merging**
