### PR TITLE
Discrimination filter

### PR DESCRIPTION
**Pull request by asnota**
@tongshuangwu, I'm creating a pull request on the main branch, as you requested. No conflicts detected.

### CODE REVIEW

**Comment by kaustubhdhole** [comment]
Earlier PR: https://github.com/GEM-benchmark/NL-Augmenter/pull/189

**Review by tongshuangwu — APPROVED** [review]
approving as this is a follow up of an earlier PR.

**Comment by kaustubhdhole** [comment]
@sebastianGehrmann reminder.

**Review by sebastianGehrmann — APPROVED** [review]
Looking great! My only nit is that maybe there is a better name than just "discrimination"? How about something like "group inequity" or so? Other than that I will approve.

**Comment by asnota** [comment]
Yes, I agree, "group inequity" is a better title for this PR - I'll change it.

**Comment by asnota** [comment]
The filter has been renamed.

**Comment by kaustubhdhole** [comment]
@asnota maybe you forgot to push the rename change?

**Comment by kaustubhdhole** [comment]
Thanks @tongshuangwu and @sebastianGehrmann. I've merged https://github.com/GEM-benchmark/NL-Augmenter/pull/280

**Comment by asnota** [comment]
@kaustubhdhole I guess you've found out already that the changes related to renaming were pulled to #280. Thank you for merging!

**Pull request closed without merging**
