### PR TITLE
add no white space perturbation

### PR DESCRIPTION
**Pull request by andreaschandra**
This perturbation removes all the white spaces in the text. It can be used to test the robustness of the model on no segmentation

### CODE REVIEW

**Review by tongshuangwu — COMMENTED** [review]
1. It seems the check has failed. Could you please fix it? Then I'm happy to re
2. The transformation seems like a bit of a stretch, in the sense that it might have broken the inherent model structure: by design, we would maybe only ask the model to deal with tokenizable sentences. I wonder what's the author's thought on this? Could you please provide some examples on how the tested `roberta` and `distillbert` model handled tokenization, and maybe add a warning on what model could benefit from this test? (e.g. if a model is using a space-based tokenization then it won't work?)

**Comment by andreaschandra** [comment]
> 1. It seems the check has failed. Could you please fix it? Then I'm happy to re
> 2. The transformation seems like a bit of a stretch, in the sense that it might have broken the inherent model structure: by design, we would maybe only ask the model to deal with tokenizable sentences. I wonder what's the author's thought on this? Could you please provide some examples on how the tested `roberta` and `distillbert` model handled tokenization, and maybe add a warning on what model could benefit from this test? (e.g. if a model is using a space-based tokenization then it won't work?)

Hi,
1. I have updated the code, kindly approve the git workflow
2. Yes, This is inspired by the languages that don't have natural separators like Chinese. I first tried on pre-trained tokenizer `bert-base-uncased`. It just worked as usual, but the number of tokens and the tokens different from usual sentence (before removing whitespace)

**Comment by uxyi** [comment]
I am not a reviewer, but the author of #49. The whitespace perturbation I added removes or adds a whitespace at random positions. The probability of a whitespace being removed or added could be assigned by `remove_prob` and `add_prob` respectively. To my understanding, your perturbation is a special case of mine (when `remove_prob=1.0` and `add_prob=0.0`), and could be covered by #49 already. Could you clarify the difference and the novelty of your perturbation?

**Comment by kaustubhdhole** [comment]
Okay, I am closing this PR since it is a part of another PR. I would encourage you to recreate another PR. You might want to take a look at some of the discussions here if they are of any use and also previously created PRs. Thank you very much for your interest! Looking forward for your PR. :)

**Pull request closed without merging**
