### PR TITLE
Issue 172 on setting CUDA flag to true or false in evaluate function for users to be able to use CPU without issues

### PR DESCRIPTION
**Pull request by timothy22000**
https://github.com/GEM-benchmark/NL-Augmenter/issues/172

### CODE REVIEW

**Comment by kaustubhdhole** [comment]
@timothy22000 thank you very much for adding this change!

**Review by kaustubhdhole — APPROVED** [review]

**Comment by AbinayaM02** [comment]
#172

**Review by AbinayaM02 — APPROVED** [review]
Change looks good. Thank you for fixing this @timothy22000.

**Comment by timothy22000** [comment]
@AbinayaM02 @kaustubhdhole It was my pleasure!

**Pull request merged**
