### PR TITLE
add tests for entity_mention_replacement_ner

### PR DESCRIPTION
**Pull request by uyaseen**
For some strange reason, the build was failing for [entity_mention_replacement_ner transformation](https://github.com/GEM-benchmark/NL-Augmenter/pull/178), therefore, tests were temporarily removed, this PR just includes the tests again for `entity_mention_replacement_ner`.

### CODE REVIEW

**Comment by uyaseen** [comment]
`RandomDeletion` still failing the build :(

```
Executing CheckSrl
Checking for keywords
Executing RandomDeletion
[nltk_data] Downloading package punkt to /home/runner/nltk_data...
F

=================================== FAILURES ===================================
_________________________ test_operation[light-light] __________________________

transformation_name = 'light', filter_name = 'light'

    def test_operation(transformation_name, filter_name):
        initialize_models()
>       execute_test_case_for_transformation(transformation_name)

test/test_main.py:154: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/test_main.py:125: in execute_test_case_for_transformation
    execute_sentence_operation_test_case(transformation, test)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

transformation = <transformations.random_deletion.transformation.RandomDeletion object at 0x7f41b5ce5cd0>
test = {'class': 'RandomDeletion', 'inputs': {'sentence': 'Andrew finally returned the French book to Chris that I bought last week'}, 'outputs': [{'sentence': 'Andrew finally returned the French book to I last week'}]}

    def execute_sentence_operation_test_case(transformation, test):
        filter_args = test["inputs"]
        outputs = test["outputs"]
        perturbs = transformation.generate(**filter_args)
        for pred_output, output in zip_longest(perturbs, outputs):
>           assert pred_output == output["sentence"], get_assert_message(
                transformation, output["sentence"], pred_output
            )
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /home/runner/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
E           AssertionError: Mis-match in expected and predicted output for RandomDeletion transformation: 
E              Expected Output: Andrew finally returned the French book to I last week 
E              Predicted Output: finally returned French book to week
E           assert 'finally retu... book to week' == 'Andrew final...o I last week'
E             - Andrew finally returned the French book to I last week
E             ? -------                 ----              -------
E             + finally returned French book to week

test/test_main.py:33: AssertionError
```

**Comment by kaustubhdhole** [comment]
@AbinayaM02 any clue? @uyaseen could you try `pytest -s --t=light --f=light` ?

**Comment by AbinayaM02** [comment]
> @AbinayaM02 any clue? @uyaseen could you try `pytest -s --t=light --f=light` ?

I pulled your code locally and ran pytest. Both the individual pytest for random_deletion and `pytest -s --t=light --f=light` passed!

@uyaseen : What's the version of python you're using? [I'm using 3.7.5]

**Comment by uyaseen** [comment]
> > @AbinayaM02 any clue? @uyaseen could you try `pytest -s --t=light --f=light` ?
> 
> I pulled your code locally and ran pytest. Both the individual pytest for random_deletion and `pytest -s --t=light --f=light` passed!
> 
> @uyaseen : What's the version of python you're using? [I'm using 3.7.5]

@AbinayaM02 the tests pass locally for me as well, I have python `3.7.11`, I am not sure why the build fails for this PR though.

**Comment by uyaseen** [comment]
> @AbinayaM02 any clue? @uyaseen could you try `pytest -s --t=light --f=light` ?

@kaustubhdhole locally the tests passed

**Comment by AbinayaM02** [comment]
Hi @uyaseen : From the log, I see that your code is not the latest (some fixes have gone in for the pytest failure). Please fetch and merge the main branch and pull the main branch into your current branch.

**Comment by uyaseen** [comment]
> Hi @uyaseen : From the log, I see that your code is not the latest (some fixes have gone in for the pytest failure). Please fetch and merge the main branch and pull the main branch into your current branch.

@AbinayaM02 Many thanks! I have synced my branch with the main branch; so I hope the tests should pass now.

> Also, make sure your transformation name is present in the test/mapper.py file in the right dictionary. I think it's already added but you can just cross-check.

The transformation is present in the `test/mapper.py`.

**Comment by uyaseen** [comment]
Dang the build failed again, something nasty is going on, I am not sure what's wrong ...
(interestingly the build was successful for the other transformation https://github.com/GEM-benchmark/NL-Augmenter/pull/239 - (both of these transformations were checked-out from the same (local) main branch))

**Comment by AbinayaM02** [comment]
> Dang the build failed again, something nasty is going on, I am not sure what's wrong ...
> (interestingly the build was successful for the other transformation #239 - (both of these transformations were checked-out from the same (local) main branch))

I think random_deletion transformation is failing. Let me pull your code and check what's happening. To give you some clarity, only light transformations' and filters' test cases are run in the workflow. If yours is a heavy transformation, you need to run
```python
pytest -s --t=<your_transformation>
```
to see if your transformation is passing the test.

**Comment by uyaseen** [comment]
> I think random_deletion transformation is failing. Let me pull your code and check what's happening. To give you some clarity, only light transformations' and filters' test cases are run in the workflow. If yours is a heavy transformation, you need to run
> 
> ```python
> pytest -s --t=<your_transformation>
> ```
> 
> to see if your transformation is passing the test.

@AbinayaM02 thanks for the explanation. Actually, locally the tests pass for both `random_deletion` and `entity_mention_replacement_ner`.

**Comment by AbinayaM02** [comment]
> > I think random_deletion transformation is failing. Let me pull your code and check what's happening. To give you some clarity, only light transformations' and filters' test cases are run in the workflow. If yours is a heavy transformation, you need to run
> > ```python
> > pytest -s --t=<your_transformation>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to see if your transformation is passing the test.
> 
> @AbinayaM02 thanks for the explanation. Actually, locally the tests pass for both `random_deletion` and `entity_mention_replacement_ner`.

Actually, I pulled your branch [entity_mention_replacement_ner_tests] and ran the tests, individually random deletion passed but for all light transformation it's failing. But when I switched to your main branch and ran the individual and light tests, both passed! Not sure, why it's failing in entity_mention_replacement_ner. Will check and update.

**Comment by AbinayaM02** [comment]
> > Edit:
> > I see that you have force-pushed your branch. After you updated your repository with fetch & merge and pulled the main into your entity_mention_replacement_ner_tests branch, you can commit your changes and do
> > ```python
> > git push origin entity_mention_replacement_ner_tests
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Could you try that once and check if the test passes?
> 
> @AbinayaM02 Many thanks for looking into this.
> So I temporarily removed the test cases for `entity_mention_replacement_ner` and the build [passes](https://github.com/GEM-benchmark/NL-Augmenter/pull/290/commits/125176487a010eaef0983576a26664661f55fdf1).
> But when I again re-added the test cases for the `entity_mention_replacement_ner`, the [build fails](https://github.com/GEM-benchmark/NL-Augmenter/pull/290/commits/9d97dddcada37453dd3d94c8ba989074ceb79b7d) again.
> This time I used `git push origin entity_mention_replacement_ner_tests` instead of forced-pushing.
> Very strange!

The issue was with random deletion not setting the super class seed!! Fixed it and now the test case passes :)

**Comment by uyaseen** [comment]
> > > Edit:
> > > I see that you have force-pushed your branch. After you updated your repository with fetch & merge and pulled the main into your entity_mention_replacement_ner_tests branch, you can commit your changes and do
> > > ```python
> > > git push origin entity_mention_replacement_ner_tests
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Could you try that once and check if the test passes?
> > 
> > 
> > @AbinayaM02 Many thanks for looking into this.
> > So I temporarily removed the test cases for `entity_mention_replacement_ner` and the build [passes](https://github.com/GEM-benchmark/NL-Augmenter/pull/290/commits/125176487a010eaef0983576a26664661f55fdf1).
> > But when I again re-added the test cases for the `entity_mention_replacement_ner`, the [build fails](https://github.com/GEM-benchmark/NL-Augmenter/pull/290/commits/9d97dddcada37453dd3d94c8ba989074ceb79b7d) again.
> > This time I used `git push origin entity_mention_replacement_ner_tests` instead of forced-pushing.
> > Very strange!
> 
> The issue was with random deletion not setting the super class seed!! Fixed it and now the test case passes :)

@AbinayaM02 Many thanks!!! Really appreciate it :)

**Comment by kaustubhdhole** [comment]
Discussed with @AbinayaM02 offline to approve this.

**Review by kaustubhdhole — APPROVED** [review]

**Pull request merged**
